#!/usr/bin/env python3

"""Generates the translated home pages: de/index.html and fr/index.html.

index.html is both the English page and the template. This script reads it,
swaps every element carrying a data-i18n path for the matching string in
i18n/<lang>.json, corrects the handful of head tags that name a language or a
URL, and writes the result into its own directory.

The point of doing this here rather than in the browser is addressability. A
static host cannot vary a response by query string, so ?lang=de returned the
same bytes as / and Google folded the two together. A directory is a real,
separate address with real, separate copy in the markup, which is what hreflang
and a self-referencing canonical need in order to mean anything.

Run it after editing index.html or either locale file:

    python3 build.py

Standard library only, like everything else here. It prints what it wrote and
exits non-zero if anything is wrong, so a broken build cannot pass unnoticed.
"""

import html
import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path


ROOT = Path(__file__).resolve().parent
TEMPLATE = ROOT / "index.html"
LOCALE_DIR = ROOT / "i18n"

ORIGIN = "https://interactive.li"

# index.html holds the English copy inline, so English is generated by not
# generating anything: the template is already the page.
SOURCE_LANGUAGE = "en"
TARGET_LANGUAGES = ("de", "fr")

# Open Graph wants language_TERRITORY, not a bare code.
OG_LOCALES = {"en": "en_US", "de": "de_DE", "fr": "fr_FR"}

# Emitted as <tag ...> with no closing tag, per the HTML5 spec.
VOID_ELEMENTS = frozenset([
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
])

# A generated page sits one directory down, so every path in it has to be
# root-absolute or it resolves against /de/ and 404s. These are the prefixes
# that are safe; anything else in an href or src fails the build.
SAFE_URL_PREFIXES = ("/", "#", "http://", "https://", "mailto:")


class TranslationError(Exception):
    """Raised for a template the translator cannot handle safely."""


def value_at(dictionary, path):
    """Resolves a dotted path such as experiences.items.generations.hook."""
    current = dictionary

    for part in path.split("."):
        if not isinstance(current, dict) or part not in current:
            return None

        current = current[part]

    return current if isinstance(current, str) else None


class Translator(HTMLParser):
    """Re-emits the template with one language's copy substituted in.

    convert_charrefs is off so that entities arrive as their own events and can
    be passed through untouched; only the strings this class substitutes are
    escaped, and only where they land.
    """

    def __init__(self, language, dictionary):
        HTMLParser.__init__(self, convert_charrefs=False)

        self.language = language
        self.dictionary = dictionary
        self.page_url = ORIGIN + "/" + language + "/"

        self.out = []
        self.missing = []

        # Set while the original text of a translated element is being
        # discarded, and holds that element's tag name.
        self._replacing = None

        # Set while inside the JSON-LD block, whose body is data, not markup.
        self._in_json_ld = False

    # -- helpers ---------------------------------------------------------

    def _emit(self, text):
        if self._replacing is None:
            self.out.append(text)

    def _translate(self, path):
        """Looks up a path, recording it when the locale has nothing for it."""
        value = value_at(self.dictionary, path)

        if value is None:
            self.missing.append(path)

        return value

    def _retarget(self, tag, attrs):
        """Applies the per-language corrections to one start tag.

        Everything here is a head tag naming a language or a URL, plus the
        switcher entry that has to read as current. Takes and returns an
        ordered list of (name, value) pairs.
        """
        lookup = dict(attrs)

        def replace(name, value):
            return [(key, value if key == name else old) for key, old in attrs]

        if tag == "html":
            return replace("lang", self.language)

        if tag == "link" and lookup.get("rel") == "canonical":
            return replace("href", self.page_url)

        if tag == "meta" and lookup.get("property") == "og:url":
            return replace("content", self.page_url)

        if tag == "meta" and lookup.get("property") == "og:locale":
            return replace("content", OG_LOCALES[self.language])

        if tag == "a" and "lang-link" in (lookup.get("class") or "").split():
            # aria-current is what the stylesheet and assistive tech both read,
            # so exactly one entry carries it and it is this page's own.
            stripped = [pair for pair in attrs if pair[0] != "aria-current"]

            if lookup.get("data-lang") == self.language:
                return stripped + [("aria-current", "true")]

            return stripped

        return attrs

    def _render_tag(self, tag, attrs, closing):
        parts = ["<", tag]

        for name, value in attrs:
            if value is None:
                parts.append(" " + name)
            else:
                parts.append(' %s="%s"' % (name, html.escape(value, quote=True)))

        parts.append(" />" if closing else ">")

        return "".join(parts)

    # -- parser events ---------------------------------------------------

    def handle_decl(self, decl):
        # Straight after the doctype, where anyone opening the file sees it
        # before anything else. A comment before the doctype would put old IE
        # into quirks mode.
        self._emit(
            "<!" + decl + ">\n"
            "<!-- GENERATED BY build.py — DO NOT EDIT.\n"
            "     Structure comes from index.html, words from i18n/%s.json.\n"
            "     Edit one of those and run: python3 build.py -->"
            % self.language
        )

    def handle_comment(self, data):
        self._emit("<!--" + data + "-->")

    def handle_pi(self, data):
        self._emit("<?" + data + ">")

    def handle_entityref(self, name):
        self._emit("&" + name + ";")

    def handle_charref(self, name):
        self._emit("&#" + name + ";")

    def handle_startendtag(self, tag, attrs):
        self._emit(self._render_tag(tag, self._retarget(tag, attrs), True))

    def handle_starttag(self, tag, attrs):
        if self._replacing is not None:
            raise TranslationError(
                "<%s> nested inside translated <%s> at line %d: data-i18n "
                "replaces an element's whole text, so it cannot hold markup."
                % (tag, self._replacing, self.getpos()[0])
            )

        attrs = self._retarget(tag, attrs)
        lookup = dict(attrs)

        # Attribute translation: "content:meta.description", several allowed,
        # separated by semicolons.
        if lookup.get("data-i18n-attr"):
            overrides = {}

            for pair in lookup["data-i18n-attr"].split(";"):
                name, sep, path = pair.partition(":")

                if not sep:
                    continue

                value = self._translate(path.strip())

                if value is not None:
                    overrides[name.strip()] = value

            attrs = [(key, overrides.get(key, old)) for key, old in attrs]

        self._emit(self._render_tag(tag, attrs, False))

        if tag == "script" and lookup.get("type") == "application/ld+json":
            self._in_json_ld = True
            return

        # Text translation. A path the locale does not carry leaves the
        # template's English in place rather than emptying the element.
        if lookup.get("data-i18n") and tag not in VOID_ELEMENTS:
            value = self._translate(lookup["data-i18n"])

            if value is not None:
                self.out.append(html.escape(value, quote=False))
                self._replacing = tag

    def handle_endtag(self, tag):
        if self._replacing is not None:
            if tag != self._replacing:
                raise TranslationError(
                    "</%s> closes translated <%s> at line %d."
                    % (tag, self._replacing, self.getpos()[0])
                )

            self._replacing = None

        self._in_json_ld = False
        self.out.append("</" + tag + ">")

    def handle_data(self, data):
        if self._in_json_ld:
            self.out.append(self._translate_json_ld(data))
            return

        self._emit(data)

    def _translate_json_ld(self, data):
        """Swaps the organisation description for this language's."""
        description = self._translate("meta.description")

        if description is None:
            return data

        payload = json.loads(data)
        payload["description"] = description

        return "\n" + json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    def result(self):
        return "".join(self.out)


def check_paths_are_absolute(markup):
    """Fails the build on a path that would break one directory down."""
    problems = []

    for match in re.finditer(r'\b(?:href|src)="([^"]*)"', markup):
        url = match.group(1)

        if url and not url.startswith(SAFE_URL_PREFIXES):
            problems.append(url)

    return problems


def main():
    template = TEMPLATE.read_text(encoding="utf-8")

    relative = check_paths_are_absolute(template)

    if relative:
        sys.stderr.write(
            "index.html carries paths that are relative to the page: %s\n"
            "A generated page sits in /de/ or /fr/, where those resolve to a "
            "directory that does not exist. Make them root-absolute.\n"
            % ", ".join(sorted(set(relative)))
        )
        return 1

    failed = False

    for language in TARGET_LANGUAGES:
        locale_file = LOCALE_DIR / (language + ".json")

        if not locale_file.exists():
            sys.stderr.write("Missing locale file: %s\n" % locale_file)
            failed = True
            continue

        dictionary = json.loads(locale_file.read_text(encoding="utf-8"))

        translator = Translator(language, dictionary)

        try:
            translator.feed(template)
            translator.close()
        except TranslationError as error:
            sys.stderr.write("%s: %s\n" % (language, error))
            failed = True
            continue

        # Every key is expected in every locale; one that is absent means the
        # page silently falls back to English, so say so rather than let it
        # ship unnoticed.
        for path in translator.missing:
            sys.stderr.write(
                "%s: no translation for %s — English left in place\n"
                % (language, path)
            )
            failed = True

        destination = ROOT / language / "index.html"
        destination.parent.mkdir(exist_ok=True)
        destination.write_text(translator.result(), encoding="utf-8")

        print("wrote %s" % destination.relative_to(ROOT))

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
